# Generated by Django 3.2.12 on 2022-03-01 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['created_time'], 'verbose_name': 'مخاطبین', 'verbose_name_plural': 'مخاطبین'},
        ),
    ]
