# Generated by Django 3.2.12 on 2022-03-25 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_auto_20220325_2156'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
